spring:
  data:
    mongodb:
      host: mongo
      port: 27017
      database: maps-comments
      username: root
      password: example
      authentication-database: admin


      uri: mongodb://root:example@mongo/maps-comments?authSource=admin
  jpa:
    hibernate:
      ddl-auto: update
server:
   port: 8050
